server:
  port: 8081
  servlet:
    context-path: /apg
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cherry-server:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: test
    password: Jime_123!
    druid:
#      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        url-pattern: /*
#      stat-view-servlet:
#        allow: 127.0.0.1
#        deny: apg-server
#        login-username: admin
#        login-password: admin
#        reset-enable: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
#  redis:
#    jedis:
#      pool:
#        min-idle: 5
#        max-active: 10
#        max-idle: 10
#        max-wait: 2000ms
#    host: apg-server
#    port: 6379
#    password: 123456
#    timeout: 1000ms
  cache:
    cache-names: redisCache
    type: redis
  main:
    banner-mode: console
  banner:
    charset: UTF-8
    location: classpath:logo.txt
  #    image:
  #      location: classpath:logo.png

  quartz:
    job-store-type: jdbc
  thymeleaf:
    cache: false #开发阶段建议关闭thymeleaf 缓存
    mode: LEGACYHTML5  #使用遗留的HTML5以去掉对html标签对校验
  devtools:
    restart:
      enabled: true  #热部署生效
      additional-paths: src/main/java\nsrc/main/resources/templates #设置重启的目录
      exclude: WEB-INF/**  #classpath目录下的WEB-INF文件夹内容修改不重启
mybatis:
  type-aliases-package: com.apgblogs.firstspringboot.entity
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
